<a href="https://colab.research.google.com/github/zqadi/Zoubeir-Qadi_Projects/blob/main/PY0101EN_4_3_LoadData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Completed by Zoubeir Qadi as part of IBM's Python for Data Science, AI & Development course on Coursera. Original Lab by Joseph Santarcangelo. Date: October 18, 2026

## About the Dataset

The table has one row for each product and several columns.

<ul>
    <li><b>OrderID</b>: A unique identifier for each order</li>
    <li><b>Product</b>: The name of the product purchased</li>
    <li><b>Category</b>: The category to which the product belongs (e.g., Electronics, Furniture, Stationery)</li>
    <li><b>Quantity</b>: The number of units purchased for that product</li>
    <li><b>Price</b>: The price per unit of the product</li>
    <li><b>Total</b>: The total cost for the product (calculated as Quantity × Price)</li>
    <li><b>OrderDate</b>: The date when the order was placed</li>
    <li><b>CustomerCity</b>: The city where the customer resides</li>
    
</ul>

You can see the dataset here:

<font size="1">
<table style="font-size:medium; border:1px solid black; border-collapse:collapse;">
  <tr>
    <th>OrderID</th>
    <th>Product</th>
    <th>Category</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Total</th>
    <th>OrderDate</th>
    <th>CustomerCity</th>
  </tr>
  <tr>
    <td>1</td>
    <td>Laptop</td>
    <td>Electronics</td>
    <td>2</td>
    <td>800</td>
    <td>1600</td>
    <td>2022-01-10</td>
    <td>New York</td>
  </tr>
  <tr>
    <td>2</td>
    <td>Smartphone</td>
    <td>Electronics</td>
    <td>3</td>
    <td>600</td>
    <td>1800</td>
    <td>2022-02-15</td>
    <td>Los Angeles</td>
  </tr>
  <tr>
    <td>3</td>
    <td>Desk Chair</td>
    <td>Furniture</td>
    <td>5</td>
    <td>150</td>
    <td>750</td>
    <td>2022-03-12</td>
    <td>Chicago</td>
  </tr>
  <tr>
    <td>4</td>
    <td>Notebook</td>
    <td>Stationery</td>
    <td>10</td>
    <td>2</td>
    <td>20</td>
    <td>2022-04-05</td>
    <td>Houston</td>
  </tr>
  <tr>
    <td>5</td>
    <td>Monitor</td>
    <td>Electronics</td>
    <td>1</td>
    <td>300</td>
    <td>300</td>
    <td>2022-05-21</td>
    <td>Miami</td>
  </tr>
</table>
</font>

<hr>

## Introduction of <code>Pandas</code>

In [ ]:
# Dependency needed to install file

%pip install xlrd openpyxl

In [ ]:
# Import required library

import pandas as pd

<ipython-input-2-90ea769ab797>:3: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

After the import command, we now have access to a large number of pre-built classes and functions. This assumes the library is installed; in our lab environment all the necessary libraries are installed. One way pandas allows you to work with data is a dataframe. Let's go through the process to go from a comma separated values (<b>.csv</b>) file to a dataframe. This variable <code>csv_path</code> stores the path of the <b>.csv</b>, that is  used as an argument to the <code>read_csv</code> function. The result is stored in the object <code>df</code>, this is a common short form used for a variable referring to a Pandas dataframe.

In [ ]:
# Read data from CSV file

# csv_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv'
# df = pd.read_csv(csv_path)

from pyodide.http import pyfetch
import pandas as pd

filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv"

async def download(url, filename):
    response = await pyfetch(url)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())


await download(filename, "Product-sales.csv")
df = pd.read_csv("Product-sales.csv")

> Note: This version of the lab is working on JupyterLite, which requires the dataset to be downloaded to the interface. While working on the downloaded version of this notebook on their local machines, the learners can simply **skip the steps above**, and simply use the URL directly in the `pandas.read_csv()` function. You can uncomment and run the statements in the cell below.

In [ ]:
#filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv"
#df = pd.read_csv(filename)

We can use the method <code>head()</code> to examine the first five rows of a dataframe:

In [ ]:
# Print first five rows of the dataframe

df.head()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

We use the path of the excel file and the function <code>read_excel</code>. The result is a data frame as before:

In [ ]:
# Read data from Excel File and print the first five rows

xlsx_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n9LOuKI9SlUa1b5zkaCMeg/Product-sales.xlsx'

await download(xlsx_path, "Product-sales.xlsx")
df = pd.read_excel("Product-sales.xlsx")
df.head()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

> Note: This version of the lab is working on JupyterLite, which requires the dataset to be downloaded to the interface. While working on the downloaded version of this notebook on their local machines, the learners can simply **skip the steps above**, and simply use the URL directly in the `pandas.read_excel()` function. You can uncomment and run the statements in the cell below.

In [ ]:
#xlsx_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n9LOuKI9SlUa1b5zkaCMeg/Product-sales.xlsx'
#df = pd.read_excel(xlsx_path)
#df.head()

We can access the column <b>Quantity</b> and assign it a new dataframe <b>x</b>:

In [ ]:
# Access to the column Length

x = df[['Quantity']]
x

   Quantity
0         2
1         3
2         5
3        10
4         1

The process is shown in the figure:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/CHIJ1eh6tYUzFsmgQIuCSA/1.PNG" width="1150">

<hr>

## Viewing Data and Accessing Data

You can also get a column as a series. You can think of a Pandas series as a 1-D dataframe. Just use one bracket:

In [ ]:
# Get the column as a series

x = df['Product']
x

0        Laptop
1    Smartphone
2    Desk Chair
3      Notebook
4       Monitor
Name: Product, dtype: object

You can also get a column as a dataframe. For example, we can assign the column <b>Quantity</b>:

In [ ]:
# Get the column as a dataframe

x = df[['Quantity']]
type(x)

pandas.core.frame.DataFrame

You can do the same thing for multiple columns; we just put the dataframe name, in this case, <code>df</code>, and the name of the multiple column headers enclosed in double brackets. The result is a new dataframe comprised of the specified columns:

In [ ]:
# Access to multiple columns

y = df[['Product','Category', 'Quantity']]
y

      Product     Category  Quantity
0      Laptop  Electronics         2
1  Smartphone  Electronics         3
2  Desk Chair    Furniture         5
3    Notebook   Stationery        10
4     Monitor  Electronics         1

The process is shown in the figure:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/BiDzVOrMQbianIz9DMum7A/2.PNG" width="1100">

One way to access unique elements is the <code>iloc</code> method, where you can access the 1st row and the 1st column as follows:

In [ ]:
# Access the value on the first row and the first column

df.iloc[0, 0]

1

You can access the 2nd row and the 1st column as follows:

In [ ]:
# Access the value on the second row and the first column

df.iloc[1,0]

2

You can access the 1st row and the 3rd column as follows:

In [ ]:
# Access the value on the first row and the third column

df.iloc[0,2]

'Electronics'

In [ ]:
# Access the value on the second row and the third column
df.iloc[1,2]

'Electronics'

This is shown in the following image

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/npw0rMu2hutg8MdOz4t_Kw/3.PNG" width="750">

You can access the column using the name as well, the following are the same as above:

In [ ]:
# Access the column using the name

df.loc[0, 'Product']

'Laptop'

In [ ]:
# Access the column using the name

df.loc[1, 'Product']

'Smartphone'

In [ ]:
# Access the column using the name

df.loc[1, 'CustomerCity']

'Los Angeles'

In [ ]:
# Access the column using the name

df.loc[1, 'Total']

1800

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/TR4-yEJdBj9NyQa5rlL6mg/4.PNG" width="750">

You can perform slicing using both the index and the name of the column:

In [ ]:
# Slicing the dataframe

df.iloc[0:2, 0:3]

   OrderID     Product     Category
0        1      Laptop  Electronics
1        2  Smartphone  Electronics

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/iyo_KV6ejpqgDxCcd3M1wg/5.PNG" width="950">

In [ ]:
# Slicing the dataframe using name

df.loc[0:2, 'OrderID':'Category']

   OrderID     Product     Category
0        1      Laptop  Electronics
1        2  Smartphone  Electronics
2        3  Desk Chair    Furniture

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/88vCcZQ8N4W_R7WyKoqoAA/6.PNG" width="750">

<hr>

## Quiz on DataFrame

Use a variable <code>q</code> to store the column <b>Price</b> as a dataframe

In [ ]:
# Write your code below and press Shift+Enter to execute
q = df[['Price']]
q

   Price
0    800
1    600
2    150
3      2
4    300

<details><summary>Click here for the solution</summary>

```python
q = df[['Price']]
q
    
```

</details>

Assign the variable <code>q</code> to the dataframe that is made up of the column <b>Product</b> and <b>Category</b>:

In [ ]:
# Write your code below and press Shift+Enter to execute

q = df[['Product', 'Category']]
q

      Product     Category
0      Laptop  Electronics
1  Smartphone  Electronics
2  Desk Chair    Furniture
3    Notebook   Stationery
4     Monitor  Electronics

<details><summary>Click here for the solution</summary>

```python
q = df[['Product', 'Category']]
q
    
```

</details>

Access the 2nd row and the 3rd column of <code>df</code>:

In [ ]:
# Write your code below and press Shift+Enter to execute
df.iloc[1, 2]

'Electronics'

<details><summary>Click here for the solution</summary>

```python
df.iloc[1, 2]
    
```

</details>

Use the following list to convert the dataframe index <code>df</code> to characters and assign it to <code>df_new</code>; find the element corresponding to the row index <code>a</code> and column  <code>'CustomerCity'</code>. Then select the rows <code>a</code> through <code>d</code> for the column  <code>'CustomerCity'</code>

In [ ]:
new_index=['a','b','c','d','e']

df_new=df
df_new.index=new_index
df_new.loc['a', 'CustomerCity']
df_new.loc['a':'d', 'CustomerCity']

a       New York
b    Los Angeles
c        Chicago
d        Houston
Name: CustomerCity, dtype: object

<details><summary>Click here for the solution</summary>

```python
df_new=df
df_new.index=new_index
df_new.loc['a', 'CustomerCity']
df_new.loc['a':'d', 'CustomerCity']
    
```

</details>

<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first lesson and hands-on lab in Python.
<hr>